remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: CodeMelted | About Me [GitHub]
description: An explanation of Mark Shaffer's (a.k.a codemelted) software engineering career.